name: chainctl CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      # Removed explicit actions/cache due to transient cache API failures.
      # Rely on setup-go's built-in caching for modules and build artifacts.

      - name: Lint
        run: |
          go install mvdan.cc/gofumpt@v0.6.0
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.2
          make fmt
          make lint

      - name: Unit tests
        run: |
          make test

      - name: Benchmarks (smoke)
        run: |
          make bench
